// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttawpzjougjsfkwwydgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YXdwempvdWdqc2Zrd3d5ZGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjA0NDUsImV4cCI6MjA1NzE5NjQ0NX0.adq3x-3ZiERdq8E8NMp4-Aq1etfshxFP1LdBhs0XN2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);